export const ExceptionCode = {
  AUTH: {
    ALREADY_EXIST_USER: 'ALREADY_EXIST_USER',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    TOKEN_FAIL: 'TOKEN_FAIL',
    NOT_EXIST_EMAIL: 'NOT_EXIST_EMAIL',
    NO_SESSION_KEY: 'NO_SESSION_KEY',
    NOT_EXIST_TOKEN: 'NOT_EXIST_TOKEN',
    NOT_MATCH_TOKEN: 'NOT_MATCH_TOKEN',
    WRONG_SESSION_KEY: 'WRONG_SESSION_KEY',
  },
  COMMON: {
    WRONG_REQUEST: 'WRONG_REQUEST',
  },
};
