@hostname = 127.0.0.1
@port = 9999
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json
@Context = auth
@hostContext = {{host}}/{{Context}}
###

###
POST {{hostContext}}/login HTTP/1.1
content-type: application/json

{
    "username":"test1@test.com",
    "password":"1234"
}
###

POST {{hostContext}}/token HTTP/1.1
content-type: application/json

{
    "username":"hanblues@gmail.com",
    "password":"1234"
}
###

GET {{hostContext}}/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbmJsdWVzQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2NzIxNDIyMDksImV4cCI6MTcwMzY5OTgwOX0.tBy4FdgZ4ogtbhLAXqpks1DemizOsNvpNEtf6R5Ydws