@hostname = 127.0.0.1
@port = 9999
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json
@Context = auth
@hostContext = {{host}}/{{Context}}
###

###
POST {{hostContext}}/login HTTP/1.1
content-type: application/json

{
    "username":"test1@test.com",
    "password":"1234"
}
###

POST {{hostContext}}/token HTTP/1.1
content-type: application/json

{
    "username":"hanblues@gmail.com",
    "password":"1234"
}
###

GET {{hostContext}}/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbmJsdWVzQGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY3MjIzNzU1MCwiZXhwIjoxNjcyMjQxMTUwfQ.g47EzHsJjdJDzUn4OETN5uRyw2MYR-oRCY1cN430sYQ
